version: '2'

services:

  haproxy:
    image: haproxy:1.7-alpine
    container_name: haproxy
    volumes:
      - ./haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg
    ports:
     - '8080:8080'
     - '1936:1936'
    depends_on:
      - nginx1
      - nginx2
      - nginx3

  nginx1:
    image: nginx:1.19-alpine
    container_name: nginx1
    volumes:
      - ./index1.html:/usr/share/nginx/html/index.html

  nginx2:
    image: nginx:1.19-alpine
    container_name: nginx2
    volumes:
      - ./index2.html:/usr/share/nginx/html/index.html

  nginx3:
    image: nginx:1.19-alpine
    container_name: nginx3
    volumes:
      - ./index3.html:/usr/share/nginx/html/index.html
