version: "3"

services:

  nginx_master:
    build:
      context: ./
      dockerfile: ./Dockerfile
    image: nginx_master
    container_name: nginx_master
    volumes:
      - ./index-master.html:/usr/share/nginx/html/index.html
      - ./keepalived-master.conf:/etc/keepalived/keepalived.conf
    networks:
      static-network:
        ipv4_address: 172.20.128.2
    cap_add: 
      - NET_ADMIN

  nginx_slave:
    build:
      context: ./
      dockerfile: ./Dockerfile
    image: nginx_slave
    container_name: nginx_slave
    volumes:
      - ./index-slave.html:/usr/share/nginx/html/index.html
      - ./keepalived-slave.conf:/etc/keepalived/keepalived.conf
    networks:
      static-network:
        ipv4_address: 172.20.128.3
    cap_add: 
        - NET_ADMIN

  haproxy:
    image: haproxy:1.7-alpine
    container_name: haproxy
    ports:
      - 4000:4000
      - 8080:8080
      - 1080:1080
    volumes:
      - ./haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg
    networks:
      - static-network

networks:
  static-network:
    name: static-net
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/16